name: ros2_jazzy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.23
  - pandas>=1.4
  - matplotlib>=3.5
  - scipy
  - opencv
  - pillow
  - jinja2<3.1
  - sphinx=5.3.0
  - readthedocs-sphinx-search=0.3.2
  - docutils=0.16
  # PyTorch 为了更好的 ARM64 兼容性和下载体验，优先从 conda-forge 安装
  - pytorch>=2.0
  - torchvision
  - pip:
    - opencv-python
    - wheel
    - typing-extensions
